export * from "./welcome-screen/welcome-screen"
export * from "./demo-screen/demo-screen"
export * from "./auth/register-screen/register-screen"
export * from "./auth/login-screen/login-screen"
export * from "./home-screen/home-screen"
export * from "./auth/loading-screen/loading-screen"
//export * from "./label-image-screen/label-image-screen"
//export * from "./gallery-screen/gallery-screen"
